export type StatusTone = 'neutral' | 'success' | 'warning' | 'danger' | 'info';
export type StatusDomain = 'server' | 'task' | 'certificate' | 'resource' | 'operation' | 'generic';

export const statusToneMaps: Record<StatusDomain, Record<string, StatusTone>> = {
  generic: {
    active: 'success',
    enabled: 'success',
    ready: 'success',
    healthy: 'success',
    success: 'success',
    ok: 'success',
    pending: 'warning',
    scheduled: 'info',
    warning: 'warning',
    degraded: 'warning',
    disabled: 'neutral',
    inactive: 'neutral',
    unknown: 'neutral',
    error: 'danger',
    failed: 'danger',
    danger: 'danger',
    running: 'info',
    processing: 'info',
  },
  server: {
    online: 'success',
    reachable: 'success',
    connected: 'success',
    installing: 'info',
    updating: 'info',
    warning: 'warning',
    degraded: 'warning',
    offline: 'danger',
    unreachable: 'danger',
    disabled: 'neutral',
    unknown: 'neutral',
  },
  task: {
    succeeded: 'success',
    success: 'success',
    completed: 'success',
    running: 'info',
    queued: 'info',
    scheduled: 'info',
    pending: 'warning',
    retrying: 'warning',
    failed_retryable: 'warning',
    failed: 'danger',
    blocked: 'danger',
    cancelled: 'neutral',
    skipped: 'neutral',
  },
  certificate: {
    valid: 'success',
    active: 'success',
    issuing: 'info',
    renewing: 'info',
    expiring: 'warning',
    expired: 'danger',
    failed: 'danger',
    revoked: 'danger',
    unknown: 'neutral',
  },
  resource: {
    running: 'success',
    active: 'success',
    available: 'success',
    pulling: 'info',
    updating: 'info',
    stale: 'warning',
    paused: 'warning',
    stopped: 'neutral',
    unused: 'neutral',
    failed: 'danger',
    error: 'danger',
  },
  operation: {
    accepted: 'info',
    queued: 'info',
    running: 'info',
    succeeded: 'success',
    success: 'success',
    completed: 'success',
    consistent: 'success',
    warning: 'warning',
    needs_attention: 'warning',
    partial_failed: 'warning',
    failed: 'danger',
    blocked: 'danger',
    cancelled: 'neutral',
    superseded: 'neutral',
  },
};

export function resolveStatusTone(domain: StatusDomain, status: string, tone?: StatusTone): StatusTone {
  const normalized = status.trim().toLowerCase().replace(/\s+/g, '_');
  return tone ?? statusToneMaps[domain][normalized] ?? statusToneMaps.generic[normalized] ?? 'neutral';
}