// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Health_FullMethodName                   = "/panel.agent.v1.AgentService/Health"
	AgentService_OSRelease_FullMethodName                = "/panel.agent.v1.AgentService/OSRelease"
	AgentService_SystemTraits_FullMethodName             = "/panel.agent.v1.AgentService/SystemTraits"
	AgentService_MetricsSnapshot_FullMethodName          = "/panel.agent.v1.AgentService/MetricsSnapshot"
	AgentService_PackageUpdates_FullMethodName           = "/panel.agent.v1.AgentService/PackageUpdates"
	AgentService_UpgradePackages_FullMethodName          = "/panel.agent.v1.AgentService/UpgradePackages"
	AgentService_PrepareRestart_FullMethodName           = "/panel.agent.v1.AgentService/PrepareRestart"
	AgentService_UFWStatus_FullMethodName                = "/panel.agent.v1.AgentService/UFWStatus"
	AgentService_UFWInstall_FullMethodName               = "/panel.agent.v1.AgentService/UFWInstall"
	AgentService_UFWEnable_FullMethodName                = "/panel.agent.v1.AgentService/UFWEnable"
	AgentService_UFWAllow_FullMethodName                 = "/panel.agent.v1.AgentService/UFWAllow"
	AgentService_UFWDelete_FullMethodName                = "/panel.agent.v1.AgentService/UFWDelete"
	AgentService_Fail2BanStatus_FullMethodName           = "/panel.agent.v1.AgentService/Fail2BanStatus"
	AgentService_ApplyFail2Ban_FullMethodName            = "/panel.agent.v1.AgentService/ApplyFail2Ban"
	AgentService_ReleaseFail2Ban_FullMethodName          = "/panel.agent.v1.AgentService/ReleaseFail2Ban"
	AgentService_RestartSystem_FullMethodName            = "/panel.agent.v1.AgentService/RestartSystem"
	AgentService_DockerContainers_FullMethodName         = "/panel.agent.v1.AgentService/DockerContainers"
	AgentService_DockerContainerLogs_FullMethodName      = "/panel.agent.v1.AgentService/DockerContainerLogs"
	AgentService_DockerContainerAction_FullMethodName    = "/panel.agent.v1.AgentService/DockerContainerAction"
	AgentService_DockerContainerDelete_FullMethodName    = "/panel.agent.v1.AgentService/DockerContainerDelete"
	AgentService_DockerImages_FullMethodName             = "/panel.agent.v1.AgentService/DockerImages"
	AgentService_DockerImagePull_FullMethodName          = "/panel.agent.v1.AgentService/DockerImagePull"
	AgentService_DockerImageDelete_FullMethodName        = "/panel.agent.v1.AgentService/DockerImageDelete"
	AgentService_DockerNetworks_FullMethodName           = "/panel.agent.v1.AgentService/DockerNetworks"
	AgentService_DockerVolumes_FullMethodName            = "/panel.agent.v1.AgentService/DockerVolumes"
	AgentService_DockerVolumeDelete_FullMethodName       = "/panel.agent.v1.AgentService/DockerVolumeDelete"
	AgentService_RuntimeWriteFiles_FullMethodName        = "/panel.agent.v1.AgentService/RuntimeWriteFiles"
	AgentService_RuntimeReload_FullMethodName            = "/panel.agent.v1.AgentService/RuntimeReload"
	AgentService_RuntimeCreateContainer_FullMethodName   = "/panel.agent.v1.AgentService/RuntimeCreateContainer"
	AgentService_RuntimeStop_FullMethodName              = "/panel.agent.v1.AgentService/RuntimeStop"
	AgentService_RuntimeRestart_FullMethodName           = "/panel.agent.v1.AgentService/RuntimeRestart"
	AgentService_RuntimeStatus_FullMethodName            = "/panel.agent.v1.AgentService/RuntimeStatus"
	AgentService_RuntimeLogs_FullMethodName              = "/panel.agent.v1.AgentService/RuntimeLogs"
	AgentService_RuntimePersistentArchive_FullMethodName = "/panel.agent.v1.AgentService/RuntimePersistentArchive"
	AgentService_RuntimePersistentRestore_FullMethodName = "/panel.agent.v1.AgentService/RuntimePersistentRestore"
	AgentService_StorageConfigureExport_FullMethodName   = "/panel.agent.v1.AgentService/StorageConfigureExport"
	AgentService_StorageArchiveDirectory_FullMethodName  = "/panel.agent.v1.AgentService/StorageArchiveDirectory"
	AgentService_StorageDeleteDirectory_FullMethodName   = "/panel.agent.v1.AgentService/StorageDeleteDirectory"
	AgentService_StorageStatus_FullMethodName            = "/panel.agent.v1.AgentService/StorageStatus"
	AgentService_StorageMountStatus_FullMethodName       = "/panel.agent.v1.AgentService/StorageMountStatus"
	AgentService_StorageEnsureDirectory_FullMethodName   = "/panel.agent.v1.AgentService/StorageEnsureDirectory"
	AgentService_RuntimeReconcile_FullMethodName         = "/panel.agent.v1.AgentService/RuntimeReconcile"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	OSRelease(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OSReleaseResponse, error)
	SystemTraits(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemTraitsResponse, error)
	MetricsSnapshot(ctx context.Context, in *MetricsSnapshotRequest, opts ...grpc.CallOption) (*MetricsSnapshotResponse, error)
	PackageUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PackageUpdatesResponse, error)
	UpgradePackages(ctx context.Context, in *PackageUpgradeRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	PrepareRestart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PrepareRestartResponse], error)
	UFWStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UFWStatusResponse, error)
	UFWInstall(ctx context.Context, in *UFWInstallRequest, opts ...grpc.CallOption) (*UFWStatusResponse, error)
	UFWEnable(ctx context.Context, in *UFWEnableRequest, opts ...grpc.CallOption) (*UFWStatusResponse, error)
	UFWAllow(ctx context.Context, in *UFWAllowRequest, opts ...grpc.CallOption) (*UFWStatusResponse, error)
	UFWDelete(ctx context.Context, in *UFWDeleteRequest, opts ...grpc.CallOption) (*UFWStatusResponse, error)
	Fail2BanStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Fail2BanStatusResponse, error)
	ApplyFail2Ban(ctx context.Context, in *Fail2BanApplyRequest, opts ...grpc.CallOption) (*Fail2BanStatusResponse, error)
	ReleaseFail2Ban(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Fail2BanStatusResponse, error)
	RestartSystem(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OKResponse, error)
	DockerContainers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DockerContainersResponse, error)
	DockerContainerLogs(ctx context.Context, in *DockerContainerLogsRequest, opts ...grpc.CallOption) (*DockerContainerLogsResponse, error)
	DockerContainerAction(ctx context.Context, in *DockerContainerActionRequest, opts ...grpc.CallOption) (*OKResponse, error)
	DockerContainerDelete(ctx context.Context, in *DockerContainerDeleteRequest, opts ...grpc.CallOption) (*OKResponse, error)
	DockerImages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DockerImagesResponse, error)
	DockerImagePull(ctx context.Context, in *DockerImagePullRequest, opts ...grpc.CallOption) (*OKResponse, error)
	DockerImageDelete(ctx context.Context, in *DockerImageDeleteRequest, opts ...grpc.CallOption) (*OKResponse, error)
	DockerNetworks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DockerNetworksResponse, error)
	DockerVolumes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DockerVolumesResponse, error)
	DockerVolumeDelete(ctx context.Context, in *DockerVolumeDeleteRequest, opts ...grpc.CallOption) (*OKResponse, error)
	RuntimeWriteFiles(ctx context.Context, in *RuntimeWriteFilesRequest, opts ...grpc.CallOption) (*OKResponse, error)
	RuntimeReload(ctx context.Context, in *RuntimeReloadRequest, opts ...grpc.CallOption) (*RuntimeReloadResponse, error)
	RuntimeCreateContainer(ctx context.Context, in *RuntimeCreateContainerRequest, opts ...grpc.CallOption) (*RuntimeCreateContainerResponse, error)
	RuntimeStop(ctx context.Context, in *RuntimeStopRequest, opts ...grpc.CallOption) (*RuntimeInstanceResponse, error)
	RuntimeRestart(ctx context.Context, in *RuntimeRestartRequest, opts ...grpc.CallOption) (*RuntimeInstanceResponse, error)
	RuntimeStatus(ctx context.Context, in *RuntimeStatusRequest, opts ...grpc.CallOption) (*RuntimeStatusResponse, error)
	RuntimeLogs(ctx context.Context, in *RuntimeLogsRequest, opts ...grpc.CallOption) (*RuntimeLogsResponse, error)
	RuntimePersistentArchive(ctx context.Context, in *RuntimePersistentArchiveRequest, opts ...grpc.CallOption) (*RuntimePersistentArchiveResponse, error)
	RuntimePersistentRestore(ctx context.Context, in *RuntimePersistentRestoreRequest, opts ...grpc.CallOption) (*RuntimePersistentRestoreResponse, error)
	StorageConfigureExport(ctx context.Context, in *StorageConfigureExportRequest, opts ...grpc.CallOption) (*OKResponse, error)
	StorageArchiveDirectory(ctx context.Context, in *StorageArchiveDirectoryRequest, opts ...grpc.CallOption) (*StorageArchiveDirectoryResponse, error)
	StorageDeleteDirectory(ctx context.Context, in *StorageDeleteDirectoryRequest, opts ...grpc.CallOption) (*OKResponse, error)
	StorageStatus(ctx context.Context, in *StorageStatusRequest, opts ...grpc.CallOption) (*StorageStatusResponse, error)
	StorageMountStatus(ctx context.Context, in *StorageMountStatusRequest, opts ...grpc.CallOption) (*StorageMountStatusResponse, error)
	StorageEnsureDirectory(ctx context.Context, in *StorageEnsureDirectoryRequest, opts ...grpc.CallOption) (*OKResponse, error)
	RuntimeReconcile(ctx context.Context, in *RuntimeReconcileRequest, opts ...grpc.CallOption) (*RuntimeReconcileResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AgentService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) OSRelease(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OSReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OSReleaseResponse)
	err := c.cc.Invoke(ctx, AgentService_OSRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SystemTraits(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemTraitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemTraitsResponse)
	err := c.cc.Invoke(ctx, AgentService_SystemTraits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) MetricsSnapshot(ctx context.Context, in *MetricsSnapshotRequest, opts ...grpc.CallOption) (*MetricsSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsSnapshotResponse)
	err := c.cc.Invoke(ctx, AgentService_MetricsSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PackageUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PackageUpdatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageUpdatesResponse)
	err := c.cc.Invoke(ctx, AgentService_PackageUpdates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpgradePackages(ctx context.Context, in *PackageUpgradeRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, AgentService_UpgradePackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PrepareRestart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PrepareRestartResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_PrepareRestart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, PrepareRestartResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_PrepareRestartClient = grpc.ServerStreamingClient[PrepareRestartResponse]

func (c *agentServiceClient) UFWStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UFWStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UFWStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_UFWStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UFWInstall(ctx context.Context, in *UFWInstallRequest, opts ...grpc.CallOption) (*UFWStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UFWStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_UFWInstall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UFWEnable(ctx context.Context, in *UFWEnableRequest, opts ...grpc.CallOption) (*UFWStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UFWStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_UFWEnable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UFWAllow(ctx context.Context, in *UFWAllowRequest, opts ...grpc.CallOption) (*UFWStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UFWStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_UFWAllow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UFWDelete(ctx context.Context, in *UFWDeleteRequest, opts ...grpc.CallOption) (*UFWStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UFWStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_UFWDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Fail2BanStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Fail2BanStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fail2BanStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_Fail2BanStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ApplyFail2Ban(ctx context.Context, in *Fail2BanApplyRequest, opts ...grpc.CallOption) (*Fail2BanStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fail2BanStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ApplyFail2Ban_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReleaseFail2Ban(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Fail2BanStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fail2BanStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ReleaseFail2Ban_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RestartSystem(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, AgentService_RestartSystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DockerContainers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DockerContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerContainersResponse)
	err := c.cc.Invoke(ctx, AgentService_DockerContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DockerContainerLogs(ctx context.Context, in *DockerContainerLogsRequest, opts ...grpc.CallOption) (*DockerContainerLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerContainerLogsResponse)
	err := c.cc.Invoke(ctx, AgentService_DockerContainerLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DockerContainerAction(ctx context.Context, in *DockerContainerActionRequest, opts ...grpc.CallOption) (*OKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, AgentService_DockerContainerAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DockerContainerDelete(ctx context.Context, in *DockerContainerDeleteRequest, opts ...grpc.CallOption) (*OKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, AgentService_DockerContainerDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DockerImages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DockerImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerImagesResponse)
	err := c.cc.Invoke(ctx, AgentService_DockerImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DockerImagePull(ctx context.Context, in *DockerImagePullRequest, opts ...grpc.CallOption) (*OKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, AgentService_DockerImagePull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DockerImageDelete(ctx context.Context, in *DockerImageDeleteRequest, opts ...grpc.CallOption) (*OKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, AgentService_DockerImageDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DockerNetworks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DockerNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerNetworksResponse)
	err := c.cc.Invoke(ctx, AgentService_DockerNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DockerVolumes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DockerVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DockerVolumesResponse)
	err := c.cc.Invoke(ctx, AgentService_DockerVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DockerVolumeDelete(ctx context.Context, in *DockerVolumeDeleteRequest, opts ...grpc.CallOption) (*OKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, AgentService_DockerVolumeDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RuntimeWriteFiles(ctx context.Context, in *RuntimeWriteFilesRequest, opts ...grpc.CallOption) (*OKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, AgentService_RuntimeWriteFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RuntimeReload(ctx context.Context, in *RuntimeReloadRequest, opts ...grpc.CallOption) (*RuntimeReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeReloadResponse)
	err := c.cc.Invoke(ctx, AgentService_RuntimeReload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RuntimeCreateContainer(ctx context.Context, in *RuntimeCreateContainerRequest, opts ...grpc.CallOption) (*RuntimeCreateContainerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeCreateContainerResponse)
	err := c.cc.Invoke(ctx, AgentService_RuntimeCreateContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RuntimeStop(ctx context.Context, in *RuntimeStopRequest, opts ...grpc.CallOption) (*RuntimeInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInstanceResponse)
	err := c.cc.Invoke(ctx, AgentService_RuntimeStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RuntimeRestart(ctx context.Context, in *RuntimeRestartRequest, opts ...grpc.CallOption) (*RuntimeInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInstanceResponse)
	err := c.cc.Invoke(ctx, AgentService_RuntimeRestart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RuntimeStatus(ctx context.Context, in *RuntimeStatusRequest, opts ...grpc.CallOption) (*RuntimeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_RuntimeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RuntimeLogs(ctx context.Context, in *RuntimeLogsRequest, opts ...grpc.CallOption) (*RuntimeLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeLogsResponse)
	err := c.cc.Invoke(ctx, AgentService_RuntimeLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RuntimePersistentArchive(ctx context.Context, in *RuntimePersistentArchiveRequest, opts ...grpc.CallOption) (*RuntimePersistentArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimePersistentArchiveResponse)
	err := c.cc.Invoke(ctx, AgentService_RuntimePersistentArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RuntimePersistentRestore(ctx context.Context, in *RuntimePersistentRestoreRequest, opts ...grpc.CallOption) (*RuntimePersistentRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimePersistentRestoreResponse)
	err := c.cc.Invoke(ctx, AgentService_RuntimePersistentRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StorageConfigureExport(ctx context.Context, in *StorageConfigureExportRequest, opts ...grpc.CallOption) (*OKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, AgentService_StorageConfigureExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StorageArchiveDirectory(ctx context.Context, in *StorageArchiveDirectoryRequest, opts ...grpc.CallOption) (*StorageArchiveDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageArchiveDirectoryResponse)
	err := c.cc.Invoke(ctx, AgentService_StorageArchiveDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StorageDeleteDirectory(ctx context.Context, in *StorageDeleteDirectoryRequest, opts ...grpc.CallOption) (*OKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, AgentService_StorageDeleteDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StorageStatus(ctx context.Context, in *StorageStatusRequest, opts ...grpc.CallOption) (*StorageStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_StorageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StorageMountStatus(ctx context.Context, in *StorageMountStatusRequest, opts ...grpc.CallOption) (*StorageMountStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageMountStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_StorageMountStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StorageEnsureDirectory(ctx context.Context, in *StorageEnsureDirectoryRequest, opts ...grpc.CallOption) (*OKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OKResponse)
	err := c.cc.Invoke(ctx, AgentService_StorageEnsureDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RuntimeReconcile(ctx context.Context, in *RuntimeReconcileRequest, opts ...grpc.CallOption) (*RuntimeReconcileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeReconcileResponse)
	err := c.cc.Invoke(ctx, AgentService_RuntimeReconcile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	Health(context.Context, *Empty) (*HealthResponse, error)
	OSRelease(context.Context, *Empty) (*OSReleaseResponse, error)
	SystemTraits(context.Context, *Empty) (*SystemTraitsResponse, error)
	MetricsSnapshot(context.Context, *MetricsSnapshotRequest) (*MetricsSnapshotResponse, error)
	PackageUpdates(context.Context, *Empty) (*PackageUpdatesResponse, error)
	UpgradePackages(context.Context, *PackageUpgradeRequest) (*CommandResponse, error)
	PrepareRestart(*Empty, grpc.ServerStreamingServer[PrepareRestartResponse]) error
	UFWStatus(context.Context, *Empty) (*UFWStatusResponse, error)
	UFWInstall(context.Context, *UFWInstallRequest) (*UFWStatusResponse, error)
	UFWEnable(context.Context, *UFWEnableRequest) (*UFWStatusResponse, error)
	UFWAllow(context.Context, *UFWAllowRequest) (*UFWStatusResponse, error)
	UFWDelete(context.Context, *UFWDeleteRequest) (*UFWStatusResponse, error)
	Fail2BanStatus(context.Context, *Empty) (*Fail2BanStatusResponse, error)
	ApplyFail2Ban(context.Context, *Fail2BanApplyRequest) (*Fail2BanStatusResponse, error)
	ReleaseFail2Ban(context.Context, *Empty) (*Fail2BanStatusResponse, error)
	RestartSystem(context.Context, *Empty) (*OKResponse, error)
	DockerContainers(context.Context, *Empty) (*DockerContainersResponse, error)
	DockerContainerLogs(context.Context, *DockerContainerLogsRequest) (*DockerContainerLogsResponse, error)
	DockerContainerAction(context.Context, *DockerContainerActionRequest) (*OKResponse, error)
	DockerContainerDelete(context.Context, *DockerContainerDeleteRequest) (*OKResponse, error)
	DockerImages(context.Context, *Empty) (*DockerImagesResponse, error)
	DockerImagePull(context.Context, *DockerImagePullRequest) (*OKResponse, error)
	DockerImageDelete(context.Context, *DockerImageDeleteRequest) (*OKResponse, error)
	DockerNetworks(context.Context, *Empty) (*DockerNetworksResponse, error)
	DockerVolumes(context.Context, *Empty) (*DockerVolumesResponse, error)
	DockerVolumeDelete(context.Context, *DockerVolumeDeleteRequest) (*OKResponse, error)
	RuntimeWriteFiles(context.Context, *RuntimeWriteFilesRequest) (*OKResponse, error)
	RuntimeReload(context.Context, *RuntimeReloadRequest) (*RuntimeReloadResponse, error)
	RuntimeCreateContainer(context.Context, *RuntimeCreateContainerRequest) (*RuntimeCreateContainerResponse, error)
	RuntimeStop(context.Context, *RuntimeStopRequest) (*RuntimeInstanceResponse, error)
	RuntimeRestart(context.Context, *RuntimeRestartRequest) (*RuntimeInstanceResponse, error)
	RuntimeStatus(context.Context, *RuntimeStatusRequest) (*RuntimeStatusResponse, error)
	RuntimeLogs(context.Context, *RuntimeLogsRequest) (*RuntimeLogsResponse, error)
	RuntimePersistentArchive(context.Context, *RuntimePersistentArchiveRequest) (*RuntimePersistentArchiveResponse, error)
	RuntimePersistentRestore(context.Context, *RuntimePersistentRestoreRequest) (*RuntimePersistentRestoreResponse, error)
	StorageConfigureExport(context.Context, *StorageConfigureExportRequest) (*OKResponse, error)
	StorageArchiveDirectory(context.Context, *StorageArchiveDirectoryRequest) (*StorageArchiveDirectoryResponse, error)
	StorageDeleteDirectory(context.Context, *StorageDeleteDirectoryRequest) (*OKResponse, error)
	StorageStatus(context.Context, *StorageStatusRequest) (*StorageStatusResponse, error)
	StorageMountStatus(context.Context, *StorageMountStatusRequest) (*StorageMountStatusResponse, error)
	StorageEnsureDirectory(context.Context, *StorageEnsureDirectoryRequest) (*OKResponse, error)
	RuntimeReconcile(context.Context, *RuntimeReconcileRequest) (*RuntimeReconcileResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAgentServiceServer) OSRelease(context.Context, *Empty) (*OSReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OSRelease not implemented")
}
func (UnimplementedAgentServiceServer) SystemTraits(context.Context, *Empty) (*SystemTraitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemTraits not implemented")
}
func (UnimplementedAgentServiceServer) MetricsSnapshot(context.Context, *MetricsSnapshotRequest) (*MetricsSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetricsSnapshot not implemented")
}
func (UnimplementedAgentServiceServer) PackageUpdates(context.Context, *Empty) (*PackageUpdatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageUpdates not implemented")
}
func (UnimplementedAgentServiceServer) UpgradePackages(context.Context, *PackageUpgradeRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradePackages not implemented")
}
func (UnimplementedAgentServiceServer) PrepareRestart(*Empty, grpc.ServerStreamingServer[PrepareRestartResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PrepareRestart not implemented")
}
func (UnimplementedAgentServiceServer) UFWStatus(context.Context, *Empty) (*UFWStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UFWStatus not implemented")
}
func (UnimplementedAgentServiceServer) UFWInstall(context.Context, *UFWInstallRequest) (*UFWStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UFWInstall not implemented")
}
func (UnimplementedAgentServiceServer) UFWEnable(context.Context, *UFWEnableRequest) (*UFWStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UFWEnable not implemented")
}
func (UnimplementedAgentServiceServer) UFWAllow(context.Context, *UFWAllowRequest) (*UFWStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UFWAllow not implemented")
}
func (UnimplementedAgentServiceServer) UFWDelete(context.Context, *UFWDeleteRequest) (*UFWStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UFWDelete not implemented")
}
func (UnimplementedAgentServiceServer) Fail2BanStatus(context.Context, *Empty) (*Fail2BanStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fail2BanStatus not implemented")
}
func (UnimplementedAgentServiceServer) ApplyFail2Ban(context.Context, *Fail2BanApplyRequest) (*Fail2BanStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyFail2Ban not implemented")
}
func (UnimplementedAgentServiceServer) ReleaseFail2Ban(context.Context, *Empty) (*Fail2BanStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseFail2Ban not implemented")
}
func (UnimplementedAgentServiceServer) RestartSystem(context.Context, *Empty) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartSystem not implemented")
}
func (UnimplementedAgentServiceServer) DockerContainers(context.Context, *Empty) (*DockerContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerContainers not implemented")
}
func (UnimplementedAgentServiceServer) DockerContainerLogs(context.Context, *DockerContainerLogsRequest) (*DockerContainerLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerContainerLogs not implemented")
}
func (UnimplementedAgentServiceServer) DockerContainerAction(context.Context, *DockerContainerActionRequest) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerContainerAction not implemented")
}
func (UnimplementedAgentServiceServer) DockerContainerDelete(context.Context, *DockerContainerDeleteRequest) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerContainerDelete not implemented")
}
func (UnimplementedAgentServiceServer) DockerImages(context.Context, *Empty) (*DockerImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerImages not implemented")
}
func (UnimplementedAgentServiceServer) DockerImagePull(context.Context, *DockerImagePullRequest) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerImagePull not implemented")
}
func (UnimplementedAgentServiceServer) DockerImageDelete(context.Context, *DockerImageDeleteRequest) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerImageDelete not implemented")
}
func (UnimplementedAgentServiceServer) DockerNetworks(context.Context, *Empty) (*DockerNetworksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerNetworks not implemented")
}
func (UnimplementedAgentServiceServer) DockerVolumes(context.Context, *Empty) (*DockerVolumesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerVolumes not implemented")
}
func (UnimplementedAgentServiceServer) DockerVolumeDelete(context.Context, *DockerVolumeDeleteRequest) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DockerVolumeDelete not implemented")
}
func (UnimplementedAgentServiceServer) RuntimeWriteFiles(context.Context, *RuntimeWriteFilesRequest) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeWriteFiles not implemented")
}
func (UnimplementedAgentServiceServer) RuntimeReload(context.Context, *RuntimeReloadRequest) (*RuntimeReloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeReload not implemented")
}
func (UnimplementedAgentServiceServer) RuntimeCreateContainer(context.Context, *RuntimeCreateContainerRequest) (*RuntimeCreateContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeCreateContainer not implemented")
}
func (UnimplementedAgentServiceServer) RuntimeStop(context.Context, *RuntimeStopRequest) (*RuntimeInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeStop not implemented")
}
func (UnimplementedAgentServiceServer) RuntimeRestart(context.Context, *RuntimeRestartRequest) (*RuntimeInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeRestart not implemented")
}
func (UnimplementedAgentServiceServer) RuntimeStatus(context.Context, *RuntimeStatusRequest) (*RuntimeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeStatus not implemented")
}
func (UnimplementedAgentServiceServer) RuntimeLogs(context.Context, *RuntimeLogsRequest) (*RuntimeLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeLogs not implemented")
}
func (UnimplementedAgentServiceServer) RuntimePersistentArchive(context.Context, *RuntimePersistentArchiveRequest) (*RuntimePersistentArchiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimePersistentArchive not implemented")
}
func (UnimplementedAgentServiceServer) RuntimePersistentRestore(context.Context, *RuntimePersistentRestoreRequest) (*RuntimePersistentRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimePersistentRestore not implemented")
}
func (UnimplementedAgentServiceServer) StorageConfigureExport(context.Context, *StorageConfigureExportRequest) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageConfigureExport not implemented")
}
func (UnimplementedAgentServiceServer) StorageArchiveDirectory(context.Context, *StorageArchiveDirectoryRequest) (*StorageArchiveDirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageArchiveDirectory not implemented")
}
func (UnimplementedAgentServiceServer) StorageDeleteDirectory(context.Context, *StorageDeleteDirectoryRequest) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageDeleteDirectory not implemented")
}
func (UnimplementedAgentServiceServer) StorageStatus(context.Context, *StorageStatusRequest) (*StorageStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageStatus not implemented")
}
func (UnimplementedAgentServiceServer) StorageMountStatus(context.Context, *StorageMountStatusRequest) (*StorageMountStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageMountStatus not implemented")
}
func (UnimplementedAgentServiceServer) StorageEnsureDirectory(context.Context, *StorageEnsureDirectoryRequest) (*OKResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorageEnsureDirectory not implemented")
}
func (UnimplementedAgentServiceServer) RuntimeReconcile(context.Context, *RuntimeReconcileRequest) (*RuntimeReconcileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuntimeReconcile not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_OSRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).OSRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_OSRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).OSRelease(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SystemTraits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SystemTraits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SystemTraits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SystemTraits(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_MetricsSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).MetricsSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_MetricsSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).MetricsSnapshot(ctx, req.(*MetricsSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PackageUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PackageUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PackageUpdates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PackageUpdates(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpgradePackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageUpgradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpgradePackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpgradePackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpgradePackages(ctx, req.(*PackageUpgradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PrepareRestart_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).PrepareRestart(m, &grpc.GenericServerStream[Empty, PrepareRestartResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_PrepareRestartServer = grpc.ServerStreamingServer[PrepareRestartResponse]

func _AgentService_UFWStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UFWStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UFWStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UFWStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UFWInstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UFWInstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UFWInstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UFWInstall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UFWInstall(ctx, req.(*UFWInstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UFWEnable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UFWEnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UFWEnable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UFWEnable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UFWEnable(ctx, req.(*UFWEnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UFWAllow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UFWAllowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UFWAllow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UFWAllow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UFWAllow(ctx, req.(*UFWAllowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UFWDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UFWDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UFWDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UFWDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UFWDelete(ctx, req.(*UFWDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Fail2BanStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Fail2BanStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Fail2BanStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Fail2BanStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ApplyFail2Ban_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Fail2BanApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ApplyFail2Ban(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ApplyFail2Ban_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ApplyFail2Ban(ctx, req.(*Fail2BanApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReleaseFail2Ban_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReleaseFail2Ban(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReleaseFail2Ban_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReleaseFail2Ban(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RestartSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RestartSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RestartSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RestartSystem(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DockerContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DockerContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DockerContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DockerContainers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DockerContainerLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerContainerLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DockerContainerLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DockerContainerLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DockerContainerLogs(ctx, req.(*DockerContainerLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DockerContainerAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DockerContainerAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DockerContainerAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DockerContainerAction(ctx, req.(*DockerContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DockerContainerDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerContainerDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DockerContainerDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DockerContainerDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DockerContainerDelete(ctx, req.(*DockerContainerDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DockerImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DockerImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DockerImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DockerImages(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DockerImagePull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerImagePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DockerImagePull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DockerImagePull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DockerImagePull(ctx, req.(*DockerImagePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DockerImageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerImageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DockerImageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DockerImageDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DockerImageDelete(ctx, req.(*DockerImageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DockerNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DockerNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DockerNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DockerNetworks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DockerVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DockerVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DockerVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DockerVolumes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DockerVolumeDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerVolumeDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DockerVolumeDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DockerVolumeDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DockerVolumeDelete(ctx, req.(*DockerVolumeDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RuntimeWriteFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeWriteFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RuntimeWriteFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RuntimeWriteFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RuntimeWriteFiles(ctx, req.(*RuntimeWriteFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RuntimeReload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RuntimeReload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RuntimeReload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RuntimeReload(ctx, req.(*RuntimeReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RuntimeCreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeCreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RuntimeCreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RuntimeCreateContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RuntimeCreateContainer(ctx, req.(*RuntimeCreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RuntimeStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RuntimeStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RuntimeStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RuntimeStop(ctx, req.(*RuntimeStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RuntimeRestart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RuntimeRestart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RuntimeRestart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RuntimeRestart(ctx, req.(*RuntimeRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RuntimeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RuntimeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RuntimeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RuntimeStatus(ctx, req.(*RuntimeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RuntimeLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RuntimeLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RuntimeLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RuntimeLogs(ctx, req.(*RuntimeLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RuntimePersistentArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimePersistentArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RuntimePersistentArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RuntimePersistentArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RuntimePersistentArchive(ctx, req.(*RuntimePersistentArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RuntimePersistentRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimePersistentRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RuntimePersistentRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RuntimePersistentRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RuntimePersistentRestore(ctx, req.(*RuntimePersistentRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StorageConfigureExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageConfigureExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StorageConfigureExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StorageConfigureExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StorageConfigureExport(ctx, req.(*StorageConfigureExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StorageArchiveDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageArchiveDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StorageArchiveDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StorageArchiveDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StorageArchiveDirectory(ctx, req.(*StorageArchiveDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StorageDeleteDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageDeleteDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StorageDeleteDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StorageDeleteDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StorageDeleteDirectory(ctx, req.(*StorageDeleteDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StorageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StorageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StorageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StorageStatus(ctx, req.(*StorageStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StorageMountStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageMountStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StorageMountStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StorageMountStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StorageMountStatus(ctx, req.(*StorageMountStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StorageEnsureDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageEnsureDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StorageEnsureDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StorageEnsureDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StorageEnsureDirectory(ctx, req.(*StorageEnsureDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RuntimeReconcile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeReconcileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RuntimeReconcile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RuntimeReconcile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RuntimeReconcile(ctx, req.(*RuntimeReconcileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panel.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AgentService_Health_Handler,
		},
		{
			MethodName: "OSRelease",
			Handler:    _AgentService_OSRelease_Handler,
		},
		{
			MethodName: "SystemTraits",
			Handler:    _AgentService_SystemTraits_Handler,
		},
		{
			MethodName: "MetricsSnapshot",
			Handler:    _AgentService_MetricsSnapshot_Handler,
		},
		{
			MethodName: "PackageUpdates",
			Handler:    _AgentService_PackageUpdates_Handler,
		},
		{
			MethodName: "UpgradePackages",
			Handler:    _AgentService_UpgradePackages_Handler,
		},
		{
			MethodName: "UFWStatus",
			Handler:    _AgentService_UFWStatus_Handler,
		},
		{
			MethodName: "UFWInstall",
			Handler:    _AgentService_UFWInstall_Handler,
		},
		{
			MethodName: "UFWEnable",
			Handler:    _AgentService_UFWEnable_Handler,
		},
		{
			MethodName: "UFWAllow",
			Handler:    _AgentService_UFWAllow_Handler,
		},
		{
			MethodName: "UFWDelete",
			Handler:    _AgentService_UFWDelete_Handler,
		},
		{
			MethodName: "Fail2BanStatus",
			Handler:    _AgentService_Fail2BanStatus_Handler,
		},
		{
			MethodName: "ApplyFail2Ban",
			Handler:    _AgentService_ApplyFail2Ban_Handler,
		},
		{
			MethodName: "ReleaseFail2Ban",
			Handler:    _AgentService_ReleaseFail2Ban_Handler,
		},
		{
			MethodName: "RestartSystem",
			Handler:    _AgentService_RestartSystem_Handler,
		},
		{
			MethodName: "DockerContainers",
			Handler:    _AgentService_DockerContainers_Handler,
		},
		{
			MethodName: "DockerContainerLogs",
			Handler:    _AgentService_DockerContainerLogs_Handler,
		},
		{
			MethodName: "DockerContainerAction",
			Handler:    _AgentService_DockerContainerAction_Handler,
		},
		{
			MethodName: "DockerContainerDelete",
			Handler:    _AgentService_DockerContainerDelete_Handler,
		},
		{
			MethodName: "DockerImages",
			Handler:    _AgentService_DockerImages_Handler,
		},
		{
			MethodName: "DockerImagePull",
			Handler:    _AgentService_DockerImagePull_Handler,
		},
		{
			MethodName: "DockerImageDelete",
			Handler:    _AgentService_DockerImageDelete_Handler,
		},
		{
			MethodName: "DockerNetworks",
			Handler:    _AgentService_DockerNetworks_Handler,
		},
		{
			MethodName: "DockerVolumes",
			Handler:    _AgentService_DockerVolumes_Handler,
		},
		{
			MethodName: "DockerVolumeDelete",
			Handler:    _AgentService_DockerVolumeDelete_Handler,
		},
		{
			MethodName: "RuntimeWriteFiles",
			Handler:    _AgentService_RuntimeWriteFiles_Handler,
		},
		{
			MethodName: "RuntimeReload",
			Handler:    _AgentService_RuntimeReload_Handler,
		},
		{
			MethodName: "RuntimeCreateContainer",
			Handler:    _AgentService_RuntimeCreateContainer_Handler,
		},
		{
			MethodName: "RuntimeStop",
			Handler:    _AgentService_RuntimeStop_Handler,
		},
		{
			MethodName: "RuntimeRestart",
			Handler:    _AgentService_RuntimeRestart_Handler,
		},
		{
			MethodName: "RuntimeStatus",
			Handler:    _AgentService_RuntimeStatus_Handler,
		},
		{
			MethodName: "RuntimeLogs",
			Handler:    _AgentService_RuntimeLogs_Handler,
		},
		{
			MethodName: "RuntimePersistentArchive",
			Handler:    _AgentService_RuntimePersistentArchive_Handler,
		},
		{
			MethodName: "RuntimePersistentRestore",
			Handler:    _AgentService_RuntimePersistentRestore_Handler,
		},
		{
			MethodName: "StorageConfigureExport",
			Handler:    _AgentService_StorageConfigureExport_Handler,
		},
		{
			MethodName: "StorageArchiveDirectory",
			Handler:    _AgentService_StorageArchiveDirectory_Handler,
		},
		{
			MethodName: "StorageDeleteDirectory",
			Handler:    _AgentService_StorageDeleteDirectory_Handler,
		},
		{
			MethodName: "StorageStatus",
			Handler:    _AgentService_StorageStatus_Handler,
		},
		{
			MethodName: "StorageMountStatus",
			Handler:    _AgentService_StorageMountStatus_Handler,
		},
		{
			MethodName: "StorageEnsureDirectory",
			Handler:    _AgentService_StorageEnsureDirectory_Handler,
		},
		{
			MethodName: "RuntimeReconcile",
			Handler:    _AgentService_RuntimeReconcile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrepareRestart",
			Handler:       _AgentService_PrepareRestart_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}

const (
	AgentReportService_Report_FullMethodName = "/panel.agent.v1.AgentReportService/Report"
)

// AgentReportServiceClient is the client API for AgentReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentReportServiceClient interface {
	Report(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentReportControl, AgentReport], error)
}

type agentReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentReportServiceClient(cc grpc.ClientConnInterface) AgentReportServiceClient {
	return &agentReportServiceClient{cc}
}

func (c *agentReportServiceClient) Report(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentReportControl, AgentReport], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentReportService_ServiceDesc.Streams[0], AgentReportService_Report_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentReportControl, AgentReport]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentReportService_ReportClient = grpc.BidiStreamingClient[AgentReportControl, AgentReport]

// AgentReportServiceServer is the server API for AgentReportService service.
// All implementations must embed UnimplementedAgentReportServiceServer
// for forward compatibility.
type AgentReportServiceServer interface {
	Report(grpc.BidiStreamingServer[AgentReportControl, AgentReport]) error
	mustEmbedUnimplementedAgentReportServiceServer()
}

// UnimplementedAgentReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentReportServiceServer struct{}

func (UnimplementedAgentReportServiceServer) Report(grpc.BidiStreamingServer[AgentReportControl, AgentReport]) error {
	return status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedAgentReportServiceServer) mustEmbedUnimplementedAgentReportServiceServer() {}
func (UnimplementedAgentReportServiceServer) testEmbeddedByValue()                            {}

// UnsafeAgentReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentReportServiceServer will
// result in compilation errors.
type UnsafeAgentReportServiceServer interface {
	mustEmbedUnimplementedAgentReportServiceServer()
}

func RegisterAgentReportServiceServer(s grpc.ServiceRegistrar, srv AgentReportServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentReportService_ServiceDesc, srv)
}

func _AgentReportService_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentReportServiceServer).Report(&grpc.GenericServerStream[AgentReportControl, AgentReport]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentReportService_ReportServer = grpc.BidiStreamingServer[AgentReportControl, AgentReport]

// AgentReportService_ServiceDesc is the grpc.ServiceDesc for AgentReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panel.agent.v1.AgentReportService",
	HandlerType: (*AgentReportServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _AgentReportService_Report_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
