package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	agentcontract "panel/internal/agent/contract"
)

const outputPath = "internal/agent/contract/contract_hash_generated.go"

func main() {
	hash, err := agentcontract.Hash(agentcontract.CurrentContract())
	if err != nil {
		fmt.Fprintf(os.Stderr, "hash agent contract: %v\n", err)
		os.Exit(1)
	}
	source, err := format.Source([]byte(fmt.Sprintf(`// Code generated by generate-agent-contract-hash; DO NOT EDIT.

package contract

func init() {
	currentContractHash = %q
}
`, hash)))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format generated contract hash: %v\n", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "create generated contract hash directory: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outputPath, source, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write generated contract hash: %v\n", err)
		os.Exit(1)
	}
}
